#服务端口
server:
  port: 8001
#服务名
spring:
  application:
    name: service-edu
  #环境设置:dev,test,prod
  profiles:
    active: dev
    #mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: '000000'
    #加上时间配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis日志:来查看SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  设置日志级别
#logging:
#  level: warn
